apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-app
  namespace: cats-prod
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cats-app
  template:
    metadata:
      labels:
        app: cats-app
    spec:
      containers:
      - name: cats-app
        image: $ACR_NAME.azurecr.io/cats-app:$TAG
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: WEB_CONCURRENCY
          value: "2"
        - name: MAX_THREADS
          value: "5"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 5