apiVersion: v1
kind: Service
metadata:
  name: cats-app
  namespace: cats-prod
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: "cats-app-v1"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: cats-app