name: Deploy Infrastructure

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'Infrastructure/**'

env:
  TF_VERSION: '1.5.0'
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  validate-and-plan:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}
        
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
        
    - name: Terraform Init
      working-directory: ./Infrastructure
      run: terraform init
      
    - name: Terraform Validate
      working-directory: ./Infrastructure
      run: terraform validate
      
    - name: Terraform Plan
      working-directory: ./Infrastructure
      run: terraform plan -out=plan.out
      
    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: Infrastructure/tfplan

  apply:
    needs: validate-and-plan
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}
        
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ env.AZURE_CREDENTIALS }}
        
    - name: Download Terraform Plan
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        path: Infrastructure
    
    - name: Rename Plan File
      run: mv Infrastructure/tfplan Infrastructure/plan.out
        
    - name: Terraform Init
      working-directory: ./Infrastructure
      run: terraform init
      
    - name: Terraform Apply
      working-directory: ./Infrastructure
      run: terraform apply --auto-approve plan.out

      
    - name: Output Terraform Data
      working-directory: ./Infrastructure
      run: |
        echo "ACR_NAME=$(terraform output -raw acr_name)" >> $GITHUB_ENV
        echo "AKS_NAME=$(terraform output -raw aks_name)" >> $GITHUB_ENV
        echo "RESOURCE_GROUP=$(terraform output -raw resource_group_name)" >> $GITHUB_ENV